config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root to: 'welcome#index'
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	validates :title, presence: true
	validates :instructions, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def new
		@recipe = Recipe.new
	end

	def create
		@recipe = Recipe.new(recipe_params)

		if @recipe.save
			redirect_to @recipe
		else
			render :new
		end
	end

	def show
		@recipe = Recipe.find(params[:id])
	end

	def index
		@recipes = Recipe.all
	end

	def edit
		@recipe = Recipe.find(params[:id])
	end

	def update
		@recipe = Recipe.find(params[:id])

		if @recipe.update_attributes(recipe_params)
			redirect_to @recipe
		else
			render :edit
		end
	end

	def destroy
		recipe = Recipe.find(params[:id])
		recipe.destroy
		redirect_to recipes_path
	end

private
	def recipe_params
		params.require(:recipe).permit(:title, :instructions)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cookbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<%= f.label :instructions %>
	<%= f.text_field :instructions %>
	<br>
	<%= f.submit 'Save' %>
<% end %>

app/views/recipes/_recipe.html.erb
<p><%= link_to recipe.title, recipe %></p>

app/views/recipes/edit.html.erb
<h1>Edit recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<h1>These are all the recipes!</h1>

<%= render @recipes %>

<%= link_to 'New recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

app/views/recipes/show.html.erb
<h1>This is a recipe</h1>

<p>Title: <%= @recipe.title %></p>
<p>Instructions: <%= @recipe.instructions %></p>

<%= link_to 'Edit', edit_recipe_path(@recipe) %>
<br>
<%= link_to 'Delete', @recipe, method: :delete %>
<br>
<%= link_to 'Back', recipes_path %>

app/views/welcome/index.html.erb
<h1>Welcome to my cookbook!</h1>

<%= link_to 'Check out my recipes', recipes_path %>